routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/user/{name}', 'UserController@userPage')->name('userPage');
Route::get('/user/{name}/written', 'UserController@written');
Route::post('/user/{name}/avatar_update', 'UserController@updateAvatar')->name('updateAvatar');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function (){
	Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
});

Route::resource('/story', 'StoryController');
Route::get('/story/grading', 'GradeController@grading')->name('grading');

app/models/Story.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Story extends Model
{
	protected $fillable = [
		'title', 'description', 'tags', 'genres', 'body', 'author_id',
	];

    /**
     * Updates links story with tags and genres.
     *  
     * @param  array  $data   
     * @return void         
     */
    public function genresAndTagsUpdate( $data ) : void
    {

        $this->genresUpdate( $data['genres'] );
        $this->tagsUpdate( $data['tags']?? null );

    }

    /**
     * Updates links story with genres.
     * 
     * @param  App\models\Story  $story  
     * @param  array             $genres
     * @return void                 
     */
    private function genresUpdate( $genres ) : void
    {

        $this->genres()->detach();

        foreach ( $genres as $genreName ) {

            $genre = Genre::where( 'name', $genreName )->first();

            $this->genres()->attach( $genre );

        }
    }
    /**
     * Updates links story with tags.
     * 
     * @param  App\models\Story  $story  
     * @param  array             $tags
     * @return void               
     */
    private function tagsUpdate( $tags ) : void
    {

        $this->tags()->detach();

        if ( is_null($tags) ) return;
 
        foreach ( $tags as $tagName ) {

            $tag = Tag::firstOrCreate( ['name' => $tagName] );

            $this->tags()->attach( $tag );

        }
    }

    //AUTHOR
    public function author()
    {
        return $this->belongsTo('App\User');
    } 

	//GENRES
	public function genres()
    {
        return $this->belongsToMany('App\models\Genre');
    }

    public function hasAnyGenres($genres)
    {
        if ($this->genres()->whereIn('name', $genres)->first()) {

            return true;

        }
        return false;
    }

    public function hasGenre($genre)
    {
        if ($this->genres()->where('name', $genre)->first()) {
            
            return true;

        }
        return false;
    }

    //TAGS
	public function tags()
    {
        return $this->belongsToMany('App\models\Tag');
    }

    public function hasAnyTags($tags)
    {
        if ($this->tags()->whereIn('name', $tags)->first()) {

            return true;

        }
        return false;
    }

    public function hasTag($tag)
    {
        if ($this->tags()->where('name', $tag)->first()) {
            
            return true;

        }
        return false;
    }
}
 

app/Http/Controllers/StoryController.php
<?php

namespace App\Http\Controllers;

use App\models\Story;
use App\models\Genre;
use App\models\Tag;
use App\User;
use App\Http\Requests\StoryRequest;

class StoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $storys = Story::all();
        return view('storys.index')->with('storys', $storys);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $genres = Genre::all();
        return view('storys.create')->with('genres', $genres);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoryRequest $request)
    {

        $data = $request->validated();

        $story = Story::create([

            'title' => $request->title,
            'author_id' => intval(auth()->user()->id),
            'body' => $request->body,
            'description' => $request->description,

        ]);

        $story->genresAndTagsUpdate( $data );

        return redirect()->route( 'story.show', $story->id );   
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
            $story = Story::find($id);

            if ( is_null($story) ) return back()->withErrors(['msg' => 'Запись не найдена']);

            return view('storys.show')->with('story', $story);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $story = Story::find($id);
        $genreCheckedList = $story->genres->pluck('name')->toArray();

        return view('storys.edit')
             ->with('story', $story)
             ->with('genres', Genre::all())
             ->with('genreCheckedList', $genreCheckedList)
             ->with('storyTags', $story->tags->all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoryRequest $request, $id)
    {
        $data = $request->validated();
        $story = Story::find($id);

        if ( !$story ) return back()->withErrors(['msg' => 'Запись не найдена'])->withInput();

        $story->update([

            'title' => $data['title'],
            'body' => $data['body'],
            'description' => $data['description'],

        ]);

        $story->genresAndTagsUpdate( $data );

        return back()->withInput()->with(['success' => 'Запись обновлена']);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $story = Story::find($id);
        $story->tags()->detach();
        $story->genres()->detach();
        $story->delete();

        return redirect()->route('userPage',$story->author->name)->with(['success' => 'Запись удолена']);
    }
}

resources/views/storys/create.blade.php
@extends('layouts.app')

@section('headers')
<script src="{{ asset('js/Tags.js') }}" defer></script>
<link rel="stylesheet" type="text/css" href="{{ asset('css/invalid.css') }}">
@endsection

@section('content') 
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">{{ __('Добавить статью') }}</div>

            <div class="card-body">
                <form method="POST" action="{{ route('story.store') }}">
                	@csrf

                	<div class="form-group row">
                        <label for="title" class="col-md-2 col-form-label text-md-right">{{ __('Название') }}</label>

                        <div class="col-md-10">
                            <input id="title" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" autocomplete="title" autofocus>

                            @error('title')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror

                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="body" class="col-md-2 col-form-label text-md-right">{{ __('Содержание') }}</label>

                        <div class="col-md-10">
                            <textarea id="body" rows="50" cols="30" class="form-control @error('body') is-invalid @enderror" name="body" autocomplete="body" autofocus>{{ old('body') }}</textarea>

                            @error('body')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col-md-2 col-form-label text-md-right">{{ __('Описание') }}</label>

                        <div class="col-md-10">
                            <textarea id="description" rows="5" cols="30" class="form-control @error('description') is-invalid @enderror" name="description"  autocomplete="description" autofocus>{{ old('description') }}</textarea>

                            @error('description')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                   @include('inc.genre_form')

                   @include('inc.tag_form')

                   <input type="hidden" name="author_id" value="{{ Auth::user()->id }}">
                    <div class="form-group row">
                        <div class="col-md-10">
                            <input type="submit" name="submit" id="submit" value="Отправить">
                        </div>
                    </div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/storys/edit.blade.php
@extends('layouts.app')

@section('headers')
<script src="{{ asset('js/Tags.js') }}" defer></script>
<link rel="stylesheet" type="text/css" href="{{ asset('css/invalid.css') }}">
@endsection

@section('content') 
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">{{ __('Изменить статью') }}</div>

            <div class="card-body">
                <form method="POST" action="{{ route('story.update', $story->id) }}">
                	@method('PATCH')
                	@csrf

                	<div class="form-group row">
                        <label for="title" class="col-md-2 col-form-label text-md-right">{{ __('Название') }}</label>

                        <div class="col-md-10">
                            <input id="title" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title', $story->title) }}" autocomplete="title" autofocus>

                            @error('title')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror

                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="body" class="col-md-2 col-form-label text-md-right">{{ __('Содержание') }}</label>

                        <div class="col-md-10">
                            <textarea id="body" rows="50" cols="30" class="form-control @error('body') is-invalid @enderror" name="body" autocomplete="body" autofocus>{{ old('body', $story->body) }}</textarea>

                            @error('body')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col-md-2 col-form-label text-md-right">{{ __('Описание') }}</label>

                        <div class="col-md-10">
                            <textarea id="description" rows="5" cols="30" class="form-control @error('description') is-invalid @enderror" name="description"  autocomplete="description" autofocus>{{ old('description', $story->description) }}</textarea>

                            @error('description')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                   @include('inc.genre_form')

                   @include('inc.tag_form')

                   <input type="hidden" name="author_id" value="{{ Auth::user()->id }}">
                    <div class="form-group row">
                        <div class="col-md-10">
                            <input type="submit" name="submit" id="submit" value="Отправить">
                        </div>
                    </div>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/storys/index.blade.php
@extends('layouts.app')

@section('content')
 	 @foreach($storys as $story)
	    <div>
	    	<a href="{{ url('/story/'.$story->id) }}">
		    	<h2>
			    	{{$story->id}}.
			   	 	{{$story->title}}
			   	 	@can('update-story', $story)
			   	 		@include('inc.story_manage')
					@endcan
		   	 	</h2>
	   	 	</a>
	   	 	<br>
	   	 	<div>
	   	 		<h3>description</h3>
	   	 		<p>
	   	 			{{$story->description}}
	   	 		</p>
	   	 	</div>
	   	 	<br>
	   	 	<div>
	   	 		<h3>Tags</h3>
	   	 		<ol class="tags_list">
	   	 		@foreach($story->tags as $tag)
	   	 			<li>{{ $tag->name }}</li>
	   	 		@endforeach
	   	 		</ol>
	   	 	</div>
	   	 	<br>
			<div>
				<h3>Genres</h3>
	   	 		<ol class="genres_list">
	   	 		@foreach($story->genres as $genre)
	   	 			<li>{{ $genre->name }}</li>
	   	 		@endforeach
	   	 		</ol>
	   	 	</div>
		</div>
		<hr>
	@endforeach
@endsection

resources/views/storys/show.blade.php
@extends('layouts.app')

@section('headers')

@endsection

@section('content')
<h1>{{$story->title}}</h1>
<a href="{{ url('/story/'.$story->id) }}">
	<h2>
		@can('update-story', $story)
   	 		@include('inc.story_manage')
   		 @endcan
	 </h2>
 </a>
<p>{{$story->body}}</p>
@endsection