routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/user/{name}', 'UserController@userPage')->name('userPage');
Route::get('/user/{name}/written', 'UserController@written');
Route::post('/user/{name}/avatar_update', 'UserController@updateAvatar')->name('updateAvatar');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function (){
	Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
});

Route::resource('/story', 'StoryController');
Route::get('/story/grading', 'GradeController@grading')->name('grading');

resources/views/inc/genre_form.blade.php
@error('genres.0')
    <span class="invalid-feedback" role="alert">
        <strong>{{ $message }}</strong>
    </span>
@enderror
@foreach($genres as $genre)
    <div class="form-group row">
        <label for="{{ $genre->name }}" class="col-md-2 col-form-label text-md-right">{{ $genre->name }}</label>

        <div class="col-md-10">
            <input type="checkbox" id="{{ $genre->name }}" class="form-control @error('genres.0') is-invalid @enderror" name="genres[]"  autocomplete="genre" value="{{ $genre->name }}"

                <?php 
                    // Checking for an Old Value
                    for ( $i=0; $i < 25; $i++ ) {
                        if ( $genre->name == old( 'genres.'.$i ) ) {
                            echo 'checked ';
                        }
                    }
                    // Checking for an Changed Values
                    if (isset($genreCheckedList)) {
                        foreach ( $genreCheckedList as $genreChecked) {
                            if ( $genreChecked == $genre->name ) {
                                echo 'checked';
                            }
                        }
                    }
                    
                ?>
            >
        </div>
    </div>
@endforeach

resources/views/inc/header.blade.php
<header>
    <div class="brand">
        <a href="{{ route('home') }}">
            <img src="" alt="{{ config('app.name', 'FanF') }}">    
        </a>
    </div>
    <nav>
        <ul class="navbar">
            <!-- Authentication Links -->
            @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @endif
            @else
                <li class="dropdown nav-item">
                    <a id="navbarDropdown" class="dropdown-lebel" href="{{ url('/user/'.Auth::user()->name) }}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        <span>{{ Auth::user()->name }}</span>
                        <div class="avathar">
                            <img src="{{ Auth::user()->getAvatar() }}" alt="av">
                        </div>
                    </a>
                    <div class="dropdown-menu">
                        <ul class="dropdown-list">
                            @can('manage-users')
                            <li class="dropdown-item">
                                <a class="" href="{{route('admin.users.index')}}">
                                    User Managment
                                </a>
                            </li>
                            @endcan
                            <li class="dropdown-item">
                                <a class="" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </li>
                        </ul>
                    </div>
                </li>
            @endguest
            <li class="theme nav-item">
                <label for="theme">Dark</label>
                <input type="checkbox" name="theme" id="theme-checkbox">
            </li>
            @auth
                <li class="nav-item">
                    <a class="" href="{{ url('/story/create') }}">
                        +
                    </a>
                </li>
            @endauth
        </ul>
    </nav>
</header>

resources/views/inc/story_manage.blade.php
<a href="{{ url('/story/'. $story->id .'/edit') }}">Редактировать</a>
<form method="post" action="{{ route('story.destroy', $story->id) }}">
    @method('DELETE')
    @csrf
    <div class="form-item">
        <button type="submit" class="btn-danger">Удолить</button>
    </div>
</form>

resources/views/inc/tag_form.blade.php
<div class="form-group row">
    <label for="tags[]" class="col-md-2 col-form-label text-md-right" id="label_for_tags">{{ __('Теги') }}</label>
    <button id="add_tag_btn" type="button" style="display: inline;">+</button>
    <ul id="tag_list" class="row col-12">
        @php $oldForm = false; @endphp

        @for($i = 0; $i < 25; $i++)
            @if( old('tags.'.$i) )
                <button id="delete_tag{{$i}}" type="button">x</button>
                <li class="col-12" id="tag{{$i}}_li">
                    <input type="text" id="tag{{$i}}" name="tags[]" value="{{ old('tags.'.intval($i)) }}" class="form-control @error('tags.'.intval($i)) is-invalid @enderror">
                    @error('tags.'.intval($i))
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    
                </li>
                @php $oldForm = true; @endphp
            @endif
        @endfor

        @if( isset($storyTags) &&  !$oldForm)
            @foreach( $storyTags as $tag )
                <button id="delete_tag{{$loop->index}}" type="button">x</button>
                <li class="col-12" id="tag{{$loop->index}}_li">
                    <input type="text" id="tag{{$loop->index}}" name="tags[]" value="{{ $tag->name }}" class="form-control @error('tags.'.$loop->index) is-invalid @enderror">
                    @error('tags.'.$loop->index)
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                    
                </li>
            @endforeach
        @endif
    </ul>
</div>