routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/user/{name}', 'UserController@userPage')->name('userPage');
Route::get('/user/{name}/written', 'UserController@written');
Route::post('/user/{name}/avatar_update', 'UserController@updateAvatar')->name('updateAvatar');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function (){
	Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
});

Route::resource('/story', 'StoryController');
Route::get('/story/grading', 'GradeController@grading')->name('grading');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'password', 'additional_info', 'avatar_path',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    /*
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    */
   public function getAvatar()
   {
      return asset(  $this->getAvatarPath(). $this->avatar_name );
   }

    public function getAvatarPath()
    {
        return 'img/avatars/';
    }

    public function clearAvatar()
    {
        $avatarPath = public_path( $this->getAvatarPath() );

        unlink( $avatarPath.$this->avatar_name );
    }

    //STIRYS
    public function storys()
    {
        return $this->hasMany('App\models\Story', 'author_id');
    }

    //ROLES
    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    public function hasAnyRoles($roles)
    {
        if ($this->roles()->whereIn('name', $roles)->first()) {

            return true;

        }
        return false;
    }

    public function hasRole($role)
    {
        if ($this->roles()->where('name', $role)->first()) {
            
            return true;

        }
        return false;
    }

    //GRADES
    public function grades()
    {
    return $this->belongsToMany('App\models\Grade');
    }

    public function hasAnyGrades($grades)
    {
        if ($this->grades()->whereIn('grade', $grades)->first()) {

            return true;

        }
        return false;
    }

    public function hasGrade($grade)
    {
        if ($this->grades()->where('grade', $grade)->first()) {
            
            return true;

        }
        return false;
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\Role;
use Gate;
use Illuminate\Http\Request;

class UsersController extends Controller
{

    public function __construct()
    {
        //$this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.users.index')->with('users', $users);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        if (Gate::denies('edit-users')) {
            return redirect(route('admin.users.index'));
        }
        $roles = Role::all();

        return view('admin.users.edit')->with([
            'user'=>$user,
            'roles'=>$roles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->roles()->sync($request->roles);

        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        /*if (Gate::denies('delite-users')) {
            return redirect(route('admin.users.index'));
        }*/
        $user->roles()->detach();
        $user->delete();

         return redirect()->route('admin.users.index');
    }

    public function userPage($name)
    {
        $user = User::where('name', $name)->first();
        return view('auth.user.user_page')->with('user', $user);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Requests\avatarUpdateRequest;
use Image;

class UserController extends Controller
{
    
    public function userPage( $username ) {

        $user = User::where('name', $username)->first();
        return view('auth.user.user_page')->with('user', $user);

    }

    public function written( $username ) {

        $user = User::where('name', $username)->first();
        return view('auth.user.user_written_storis_list')->with('user', $user);

    }

    public function updateAvatar( avatarUpdateRequest $request, $username ) {

        $user = User::where('name', $username)->first();
        $user->can('update-profile', $user);

        if ( $user->avatar_name != 'User_def_avatar.png' ) { 

            $user->clearAvatar();

        }

        $avatar = $request->file('avatar');

        $fileName = time() . '_' . $user->name . '.' . $avatar->getClientOriginalExtension();

        Image::make($avatar)->resize(300, 300)->save( public_path( $user->getAvatarPath() ) . $fileName);

        $user->avatar_name = $fileName;
        $user->save();

        return back();
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Edit users</div>
                <form action="{{route('admin.users.update', $user)}}" method="POST">
                	@csrf
                	{{method_field('PUT')}}
                	@foreach($roles as $role)
                	 <div class="form-check">
                	 	<input type="checkbox" name="roles[]" value="{{ $role->id }}">
                	 	<label>{{ $role->name }}</label>
                	 </div>
                	@endforeach
                	<button type="submit">
                		Update
                	</button>
                </form>
            <div class="card-body">
               
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Users</div>
                @foreach($users as $user)
                    <div><a href="{{ url('/user/'.$user->name) }}">{{$user->name}}</a> - {{implode(', ', $user->roles()->get()->pluck('name')->toArray())}}</div>

                    @can('edit-users')

                    <a href="{{route('admin.users.edit', $user->id)}}"><button>Edit</button></a>

                    @endcan

                    @can('delete-users')
                    
                    <form action="{{Route('admin.users.destroy', $user)}}" method="POST">
                    @csrf
                    {{method_field('DELETE')}}
                        <button type="submit">
                            Delite
                        </button>
                    </form>

                    @endcan
                    <hr>
                @endforeach
            <div class="card-body">
               
            </div>
        </div>
    </div>
</div>
@endsection